/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

//import 
import JTextField_Especial.JtxtCedula;
import com.bolivia.label.CLabel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JPasswordField;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;


/**
 *
 * @author velez
 */
public class Vista_Registro_Usuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form Vista_Registro_Usuario
     */
    public Vista_Registro_Usuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ventana_EditarUsuario = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtUsuario_RegisEdit = new javax.swing.JTextField();
        txtContra_RegisEdit = new javax.swing.JPasswordField();
        txtConfirmarContra_RegisEdit = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        cmb_TipoUedit = new javax.swing.JComboBox<>();
        btn_editarUsuario = new javax.swing.JButton();
        btn_cancelarEditUs = new javax.swing.JButton();
        lbl_mensajeContraDialog = new javax.swing.JLabel();
        lbl_fotoRegistroEdit = new com.bolivia.label.CLabel();
        btn_examinarFotoEdit = new javax.swing.JButton();
        txtCedula_RegisEdit = new JTextField_Especial.JtxtCedula();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_usuarios = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        btn_eliminarUsuario = new javax.swing.JButton();
        lbl_mensajeUsuarioDialog = new javax.swing.JLabel();
        jPopupMenuEditarUsuarios = new javax.swing.JPopupMenu();
        item_limpiarCamposEditUs = new javax.swing.JMenuItem();
        item_imprimirListaEditUs = new javax.swing.JMenuItem();
        item_cerrarVentanaEditUs = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_NombreUsuario = new javax.swing.JTextField();
        txt_Contrasenia = new javax.swing.JPasswordField();
        txt_confirmarContra = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        cmb_TipoU = new javax.swing.JComboBox<>();
        btn_registrarUsuario = new javax.swing.JButton();
        btn_cancelarRegistroUsuario = new javax.swing.JButton();
        lbl_mensajeContraseña = new javax.swing.JLabel();
        lbl_mensajeUsuario = new javax.swing.JLabel();
        lbl_fotoRegistro = new com.bolivia.label.CLabel();
        btn_examinarFoto = new javax.swing.JButton();
        txtCedulaEmp_Registro = new JTextField_Especial.JtxtCedula();
        btn_ListaUsuarios = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        Ventana_EditarUsuario.setTitle("Editar Usuario");
        Ventana_EditarUsuario.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        Ventana_EditarUsuario.setResizable(false);

        jPanel3.setBackground(new java.awt.Color(40, 40, 40));

        jLabel3.setFont(new java.awt.Font("Poiret One", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Editar Usuarios ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(400, 400, 400))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setComponentPopupMenu(jPopupMenuEditarUsuarios);

        jLabel8.setFont(new java.awt.Font("Poiret One", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(40, 40, 40));
        jLabel8.setText("Cédula");

        jLabel9.setFont(new java.awt.Font("Poiret One", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(40, 40, 40));
        jLabel9.setText("Usuario");

        jLabel10.setFont(new java.awt.Font("Poiret One", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(40, 40, 40));
        jLabel10.setText("Contraseña");

        jLabel11.setFont(new java.awt.Font("Poiret One", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(40, 40, 40));
        jLabel11.setText("Confirmar");

        jLabel12.setFont(new java.awt.Font("Poiret One", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(40, 40, 40));
        jLabel12.setText("Acceso");

        cmb_TipoUedit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Estandar" }));

        btn_editarUsuario.setText("Editar Usuario");

        btn_cancelarEditUs.setText("Cancelar");

        lbl_mensajeContraDialog.setForeground(new java.awt.Color(255, 51, 51));
        lbl_mensajeContraDialog.setText("Las contraseñas no coinciden");

        lbl_fotoRegistroEdit.setText("");

        btn_examinarFotoEdit.setText("Examinar");

        tbl_usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo Usuario", "Cedula Empleado", "Nombres Empleado", "Nombre de Usuario", "Contraseña", "Tipo Usuario"
            }
        ));
        jScrollPane1.setViewportView(tbl_usuarios);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("Tabala de Datos de Usuarios");

        btn_eliminarUsuario.setText("Eliminar Usuario");

        lbl_mensajeUsuarioDialog.setForeground(new java.awt.Color(255, 51, 51));
        lbl_mensajeUsuarioDialog.setText("Las contraseñas no coinciden");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_mensajeContraDialog)
                                .addComponent(txtConfirmarContra_RegisEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtCedula_RegisEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtContra_RegisEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_mensajeUsuarioDialog)
                                    .addComponent(txtUsuario_RegisEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(lbl_fotoRegistroEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addGap(110, 110, 110))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(btn_examinarFotoEdit)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(btn_editarUsuario)
                        .addGap(38, 38, 38)
                        .addComponent(btn_cancelarEditUs)
                        .addGap(37, 37, 37)
                        .addComponent(btn_eliminarUsuario))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmb_TipoUedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_fotoRegistroEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_examinarFotoEdit))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtCedula_RegisEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtUsuario_RegisEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addComponent(lbl_mensajeUsuarioDialog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtContra_RegisEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(31, 31, 31))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtConfirmarContra_RegisEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_mensajeContraDialog)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(cmb_TipoUedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_eliminarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancelarEditUs, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_editarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout Ventana_EditarUsuarioLayout = new javax.swing.GroupLayout(Ventana_EditarUsuario.getContentPane());
        Ventana_EditarUsuario.getContentPane().setLayout(Ventana_EditarUsuarioLayout);
        Ventana_EditarUsuarioLayout.setHorizontalGroup(
            Ventana_EditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Ventana_EditarUsuarioLayout.setVerticalGroup(
            Ventana_EditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Ventana_EditarUsuarioLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        item_limpiarCamposEditUs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        item_limpiarCamposEditUs.setText("Limpiar Campos");
        jPopupMenuEditarUsuarios.add(item_limpiarCamposEditUs);

        item_imprimirListaEditUs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        item_imprimirListaEditUs.setText("Imprimir Lista Usuarios");
        item_imprimirListaEditUs.setToolTipText("");
        jPopupMenuEditarUsuarios.add(item_imprimirListaEditUs);

        item_cerrarVentanaEditUs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        item_cerrarVentanaEditUs.setText("Salir ");
        jPopupMenuEditarUsuarios.add(item_cerrarVentanaEditUs);

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Poiret One", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(40, 40, 40));
        jLabel4.setText("Cédula");

        jLabel5.setFont(new java.awt.Font("Poiret One", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(40, 40, 40));
        jLabel5.setText("Usuario");

        jLabel6.setFont(new java.awt.Font("Poiret One", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(40, 40, 40));
        jLabel6.setText("Contraseña");

        jLabel7.setFont(new java.awt.Font("Poiret One", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(40, 40, 40));
        jLabel7.setText("Confirmar");

        jLabel2.setFont(new java.awt.Font("Poiret One", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(40, 40, 40));
        jLabel2.setText("Acceso");

        cmb_TipoU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Estandar" }));

        btn_registrarUsuario.setText("Registrar");

        btn_cancelarRegistroUsuario.setText("Cancelar");

        lbl_mensajeContraseña.setForeground(new java.awt.Color(255, 51, 51));
        lbl_mensajeContraseña.setText("Las contraseñas no coinciden");

        lbl_mensajeUsuario.setForeground(new java.awt.Color(255, 51, 51));
        lbl_mensajeUsuario.setText("Este usuario ya existe");

        lbl_fotoRegistro.setText("");

        btn_examinarFoto.setText("Examinar");

        btn_ListaUsuarios.setText("Registros");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(111, 111, 111)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_NombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lbl_mensajeUsuario)
                            .addGap(58, 58, 58)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Contrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn_registrarUsuario)
                                        .addGap(4, 4, 4)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_confirmarContra, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_mensajeContraseña)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(btn_cancelarRegistroUsuario))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCedulaEmp_Registro, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmb_TipoU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_examinarFoto)
                        .addGap(116, 116, 116))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(lbl_fotoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_ListaUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(76, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_fotoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_examinarFoto))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtCedulaEmp_Registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_NombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addComponent(lbl_mensajeUsuario)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_Contrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_confirmarContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addComponent(lbl_mensajeContraseña)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cmb_TipoU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_registrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancelarRegistroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ListaUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        jPanel2.setBackground(new java.awt.Color(40, 40, 40));

        jLabel1.setFont(new java.awt.Font("Poiret One", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registrar Usuario");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /*
    ----CAMPOS DE LA VISTA PRINCIPAN DE USUARIOS----
    */
    //CAMPOS DE TEXTO
    /************************TxtCedulaEmp_Registro(****************************/
    public JtxtCedula getTxtCedulaEmp_Registro() {
        return txtCedulaEmp_Registro;
    }

    public void setTxtCedulaEmp_Registro(JtxtCedula txtCedulaEmp_Registro) {
        this.txtCedulaEmp_Registro = txtCedulaEmp_Registro;
    }
    /************************Txt_Contrasenia()*********************************/
    public JPasswordField getTxt_Contrasenia() {
        return txt_Contrasenia;
    }

    public void setTxt_Contrasenia(JPasswordField txt_Contrasenia) {
        this.txt_Contrasenia = txt_Contrasenia;
    }
    /*************************Txt_NombreUsuario()******************************/
    public JTextField getTxt_NombreUsuario() {
        return txt_NombreUsuario;
    }

    public void setTxt_NombreUsuario(JTextField txt_NombreUsuario) {
        this.txt_NombreUsuario = txt_NombreUsuario;
    }
    /*************************Txt_confirmarContra()****************************/
    public JPasswordField getTxt_confirmarContra() {
        return txt_confirmarContra;
    }

    public void setTxt_confirmarContra(JPasswordField txt_confirmarContra) {
        this.txt_confirmarContra = txt_confirmarContra;
    }
    
    //LABELES DE MENSAJE
    /**************************Lbl_fotoRegistro()******************************/
    public CLabel getLbl_fotoRegistro() {
        return lbl_fotoRegistro;
    }

    public void setLbl_fotoRegistro(CLabel lbl_fotoRegistro) {
        this.lbl_fotoRegistro = lbl_fotoRegistro;
    }
    /*************************Lbl_mensajeContraseña()**************************/
    public JLabel getLbl_mensajeContraseña() {
        return lbl_mensajeContraseña;
    }

    public void setLbl_mensajeContraseña(JLabel lbl_mensajeContraseña) {
        this.lbl_mensajeContraseña = lbl_mensajeContraseña;
    }
    /***********************Lbl_mensajeUsuario()*******************************/
    public JLabel getLbl_mensajeUsuario() {
        return lbl_mensajeUsuario;
    }

    public void setLbl_mensajeUsuario(JLabel lbl_mensajeUsuario) {
        this.lbl_mensajeUsuario = lbl_mensajeUsuario;
    }
    
    //BOTONES y COMBOBOX
    /***********************Btn_ListaUsuarios()********************************/
    public JButton getBtn_ListaUsuarios() {
        return btn_ListaUsuarios;
    }

    public void setBtn_ListaUsuarios(JButton btn_ListaUsuarios) {
        this.btn_ListaUsuarios = btn_ListaUsuarios;
    }
    /*******************Btn_cancelarRegistroUsuario()**************************/
    public JButton getBtn_cancelarRegistroUsuario() {
        return btn_cancelarRegistroUsuario;
    }

    public void setBtn_cancelarRegistroUsuario(JButton btn_cancelarRegistroUsuario) {
        this.btn_cancelarRegistroUsuario = btn_cancelarRegistroUsuario;
    }
    /*************************Btn_examinarFoto()*******************************/
    public JButton getBtn_examinarFoto() {
        return btn_examinarFoto;
    }

    public void setBtn_examinarFoto(JButton btn_examinarFoto) {
        this.btn_examinarFoto = btn_examinarFoto;
    }
    /************************Btn_examinarFoto()********************************/
    public JButton getBtn_registrarUsuario() {
        return btn_registrarUsuario;
    }

    public void setBtn_registrarUsuario(JButton btn_registrarUsuario) {
        this.btn_registrarUsuario = btn_registrarUsuario;
    }
    /****************ComboBox<String> getCmb_TipoU()***************************/
    public JComboBox<String> getCmb_TipoU() {
        return cmb_TipoU;
    }

    public void setCmb_TipoU(JComboBox<String> cmb_TipoU) {
        this.cmb_TipoU = cmb_TipoU;
    }

    public JDialog getVentana_EditarUsuario() {
        return Ventana_EditarUsuario;
    }

    /*---ELEMENTOS DEL DIALOG USUARIO---*/
    public void setVentana_EditarUsuario(JDialog Ventana_EditarUsuario) {    
        this.Ventana_EditarUsuario = Ventana_EditarUsuario;
    }
    //CAMPOS DE TEXTO DIALOG
    /*****************************************************************************/
    public JtxtCedula getTxtCedula_RegisEdit() {   
        return txtCedula_RegisEdit;
    }

    public void setTxtCedula_RegisEdit(JtxtCedula txtCedula_RegisEdit) {
        this.txtCedula_RegisEdit = txtCedula_RegisEdit;
    }
    /*****************************************************************************/
    public JPasswordField getTxtConfirmarContra_RegisEdit() {
        return txtConfirmarContra_RegisEdit;
    }

    public void setTxtConfirmarContra_RegisEdit(JPasswordField txtConfirmarContra_RegisEdit) {
        this.txtConfirmarContra_RegisEdit = txtConfirmarContra_RegisEdit;
    }
    /*****************************************************************************/
    public JPasswordField getTxtContra_RegisEdit() {
        return txtContra_RegisEdit;
    }

    public void setTxtContra_RegisEdit(JPasswordField txtContra_RegisEdit) {
        this.txtContra_RegisEdit = txtContra_RegisEdit;
    }
    /*****************************************************************************/
    public JTextField getTxtUsuario_RegisEdit() {
        return txtUsuario_RegisEdit;
    }
    
    public void setTxtUsuario_RegisEdit(JTextField txtUsuario_RegisEdit) {
        this.txtUsuario_RegisEdit = txtUsuario_RegisEdit;
    }
    
    //LABELES DE MENSAJE DIALOG
    /*****************************************************************************/
    public CLabel getLbl_fotoRegistroEdit() {
        return lbl_fotoRegistroEdit;
    }

    public void setLbl_fotoRegistroEdit(CLabel lbl_fotoRegistroEdit) {
        this.lbl_fotoRegistroEdit = lbl_fotoRegistroEdit;
    }
    /*****************************************************************************/
    public JLabel getLbl_mensajeContraDialog() {
        return lbl_mensajeContraDialog;
    }

    public void setLbl_mensajeContraDialog(JLabel lbl_mensajeContraDialog) {
        this.lbl_mensajeContraDialog = lbl_mensajeContraDialog;
    }
    /*****************************************************************************/
    public JLabel getLbl_mensajeUsuarioDialog() {
        return lbl_mensajeUsuarioDialog;
    }

    public void setLbl_mensajeUsuarioDialog(JLabel lbl_mensajeUsuarioDialog) {
        this.lbl_mensajeUsuarioDialog = lbl_mensajeUsuarioDialog;
    }
    /*****************************************************************************/
    public JTable getTbl_usuarios() {
        return tbl_usuarios;
    }

    public void setTbl_usuarios(JTable tbl_usuarios) {
        this.tbl_usuarios = tbl_usuarios;
    }
    
    //BOTONES Y COMOBOX DE DIALOG
    /*****************************************************************************/
    public JButton getBtn_cancelarEditUs() {
        return btn_cancelarEditUs;
    }

    public void setBtn_cancelarEditUs(JButton btn_cancelarEditUs) {
        this.btn_cancelarEditUs = btn_cancelarEditUs;
    }
    /*****************************************************************************/
    public JButton getBtn_editarUsuario() {
        return btn_editarUsuario;
    }

    public void setBtn_editarUsuario(JButton btn_editarUsuario) {
        this.btn_editarUsuario = btn_editarUsuario;
    }
    /*****************************************************************************/
    public JButton getBtn_eliminarUsuario() {
        return btn_eliminarUsuario;
    }

    public void setBtn_eliminarUsuario(JButton btn_eliminarUsuario) {
        this.btn_eliminarUsuario = btn_eliminarUsuario;
    }
    /*****************************************************************************/
    public JButton getBtn_examinarFotoEdit() {
        return btn_examinarFotoEdit;
    }

    public void setBtn_examinarFotoEdit(JButton btn_examinarFotoEdit) {
        this.btn_examinarFotoEdit = btn_examinarFotoEdit;
    }
    /*****************************************************************************/
    public JComboBox<String> getCmb_TipoUedit() {
        return cmb_TipoUedit;
    }

    public void setCmb_TipoUedit(JComboBox<String> cmb_TipoUedit) {
        this.cmb_TipoUedit = cmb_TipoUedit;
    }
    

    //POUP MENU ITEMS
    public JMenuItem getItem_cerrarVentanaEditUs() {
        return item_cerrarVentanaEditUs;
    }

    public void setItem_cerrarVentanaEditUs(JMenuItem item_cerrarVentanaEditUs) {
        this.item_cerrarVentanaEditUs = item_cerrarVentanaEditUs;
    }

    public JMenuItem getItem_imprimirListaEditUs() {
        return item_imprimirListaEditUs;
    }

    public void setItem_imprimirListaEditUs(JMenuItem item_imprimirListaEditUs) {
        this.item_imprimirListaEditUs = item_imprimirListaEditUs;
    }

    public JMenuItem getItem_limpiarCamposEditUs() {
        return item_limpiarCamposEditUs;
    }

    public void setItem_limpiarCamposEditUs(JMenuItem item_limpiarCamposEditUs) {
        this.item_limpiarCamposEditUs = item_limpiarCamposEditUs;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Ventana_EditarUsuario;
    private javax.swing.JButton btn_ListaUsuarios;
    private javax.swing.JButton btn_cancelarEditUs;
    private javax.swing.JButton btn_cancelarRegistroUsuario;
    private javax.swing.JButton btn_editarUsuario;
    private javax.swing.JButton btn_eliminarUsuario;
    private javax.swing.JButton btn_examinarFoto;
    private javax.swing.JButton btn_examinarFotoEdit;
    private javax.swing.JButton btn_registrarUsuario;
    private javax.swing.JComboBox<String> cmb_TipoU;
    private javax.swing.JComboBox<String> cmb_TipoUedit;
    private javax.swing.JMenuItem item_cerrarVentanaEditUs;
    private javax.swing.JMenuItem item_imprimirListaEditUs;
    private javax.swing.JMenuItem item_limpiarCamposEditUs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenuEditarUsuarios;
    private javax.swing.JScrollPane jScrollPane1;
    private com.bolivia.label.CLabel lbl_fotoRegistro;
    private com.bolivia.label.CLabel lbl_fotoRegistroEdit;
    private javax.swing.JLabel lbl_mensajeContraDialog;
    private javax.swing.JLabel lbl_mensajeContraseña;
    private javax.swing.JLabel lbl_mensajeUsuario;
    private javax.swing.JLabel lbl_mensajeUsuarioDialog;
    private javax.swing.JTable tbl_usuarios;
    private JTextField_Especial.JtxtCedula txtCedulaEmp_Registro;
    private JTextField_Especial.JtxtCedula txtCedula_RegisEdit;
    private javax.swing.JPasswordField txtConfirmarContra_RegisEdit;
    private javax.swing.JPasswordField txtContra_RegisEdit;
    private javax.swing.JTextField txtUsuario_RegisEdit;
    private javax.swing.JPasswordField txt_Contrasenia;
    private javax.swing.JTextField txt_NombreUsuario;
    private javax.swing.JPasswordField txt_confirmarContra;
    // End of variables declaration//GEN-END:variables
}
