/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mvc.vista;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author velez
 */
public class Vista_Pagina_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Vista_Pagina_Principal
     */
    public Vista_Pagina_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pnl_btnClientes = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnl_btnJuicios = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pnl_btnAudiencias = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pnl_btnCitas = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pnl_btnReportes = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pnl_btnSalir = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbl_FotoUsuario = new com.bolivia.label.CLabel();
        lbl_NombreUsuario = new javax.swing.JLabel();
        pnl_btnAddpersona = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        pnl_btnInicio = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        pnl_btnAddempleado = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        pnl_btnAddusuario = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Btn_minimizarLogin = new javax.swing.JButton();
        Btn_cerrarLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        pnl_btnClientes.setBackground(new java.awt.Color(255, 255, 255));
        pnl_btnClientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 40, 40), 2));
        pnl_btnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_btnClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_btnClientesMouseExited(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(40, 40, 40));
        jLabel3.setFont(new java.awt.Font("Yu Gothic Light", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(40, 40, 40));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Add_cliente120.png"))); // NOI18N
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel2.setFont(new java.awt.Font("Poiret One", 1, 24)); // NOI18N
        jLabel2.setText("Clientes");

        javax.swing.GroupLayout pnl_btnClientesLayout = new javax.swing.GroupLayout(pnl_btnClientes);
        pnl_btnClientes.setLayout(pnl_btnClientesLayout);
        pnl_btnClientesLayout.setHorizontalGroup(
            pnl_btnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_btnClientesLayout.createSequentialGroup()
                .addGroup(pnl_btnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_btnClientesLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_btnClientesLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel2)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        pnl_btnClientesLayout.setVerticalGroup(
            pnl_btnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_btnClientesLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_btnJuicios.setBackground(new java.awt.Color(255, 255, 255));
        pnl_btnJuicios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 40, 40), 2));
        pnl_btnJuicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_btnJuiciosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_btnJuiciosMouseExited(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(40, 40, 40));
        jLabel6.setFont(new java.awt.Font("Yu Gothic Light", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(40, 40, 40));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Add_juicios.png"))); // NOI18N
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel7.setFont(new java.awt.Font("Poiret One", 1, 24)); // NOI18N
        jLabel7.setText("Juicios");

        javax.swing.GroupLayout pnl_btnJuiciosLayout = new javax.swing.GroupLayout(pnl_btnJuicios);
        pnl_btnJuicios.setLayout(pnl_btnJuiciosLayout);
        pnl_btnJuiciosLayout.setHorizontalGroup(
            pnl_btnJuiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_btnJuiciosLayout.createSequentialGroup()
                .addGroup(pnl_btnJuiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_btnJuiciosLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_btnJuiciosLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel7)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        pnl_btnJuiciosLayout.setVerticalGroup(
            pnl_btnJuiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_btnJuiciosLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_btnAudiencias.setBackground(new java.awt.Color(255, 255, 255));
        pnl_btnAudiencias.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 40, 40), 2));
        pnl_btnAudiencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_btnAudienciasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_btnAudienciasMouseExited(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(40, 40, 40));
        jLabel8.setFont(new java.awt.Font("Yu Gothic Light", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(40, 40, 40));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Add_Audiencias.png"))); // NOI18N
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel9.setFont(new java.awt.Font("Poiret One", 1, 24)); // NOI18N
        jLabel9.setText("    Audiencias");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnl_btnAudienciasLayout = new javax.swing.GroupLayout(pnl_btnAudiencias);
        pnl_btnAudiencias.setLayout(pnl_btnAudienciasLayout);
        pnl_btnAudienciasLayout.setHorizontalGroup(
            pnl_btnAudienciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_btnAudienciasLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(pnl_btnAudienciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );
        pnl_btnAudienciasLayout.setVerticalGroup(
            pnl_btnAudienciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_btnAudienciasLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pnl_btnCitas.setBackground(new java.awt.Color(255, 255, 255));
        pnl_btnCitas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 40, 40), 2));
        pnl_btnCitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_btnCitasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_btnCitasMouseExited(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(40, 40, 40));
        jLabel10.setFont(new java.awt.Font("Yu Gothic Light", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(40, 40, 40));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Add_cita.png"))); // NOI18N
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel11.setFont(new java.awt.Font("Poiret One", 1, 24)); // NOI18N
        jLabel11.setText("Citas");

        javax.swing.GroupLayout pnl_btnCitasLayout = new javax.swing.GroupLayout(pnl_btnCitas);
        pnl_btnCitas.setLayout(pnl_btnCitasLayout);
        pnl_btnCitasLayout.setHorizontalGroup(
            pnl_btnCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_btnCitasLayout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(pnl_btnCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_btnCitasLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_btnCitasLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(95, 95, 95))))
        );
        pnl_btnCitasLayout.setVerticalGroup(
            pnl_btnCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_btnCitasLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pnl_btnReportes.setBackground(new java.awt.Color(255, 255, 255));
        pnl_btnReportes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 40, 40), 2));
        pnl_btnReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_btnReportesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_btnReportesMouseExited(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(40, 40, 40));
        jLabel12.setFont(new java.awt.Font("Yu Gothic Light", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(40, 40, 40));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Add_reporte.png"))); // NOI18N
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel13.setFont(new java.awt.Font("Poiret One", 1, 24)); // NOI18N
        jLabel13.setText("Reportes");

        javax.swing.GroupLayout pnl_btnReportesLayout = new javax.swing.GroupLayout(pnl_btnReportes);
        pnl_btnReportes.setLayout(pnl_btnReportesLayout);
        pnl_btnReportesLayout.setHorizontalGroup(
            pnl_btnReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_btnReportesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(80, 80, 80))
            .addGroup(pnl_btnReportesLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        pnl_btnReportesLayout.setVerticalGroup(
            pnl_btnReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_btnReportesLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pnl_btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        pnl_btnSalir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 40, 40), 2));
        pnl_btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_btnSalirMouseExited(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(40, 40, 40));
        jLabel14.setFont(new java.awt.Font("Yu Gothic Light", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(40, 40, 40));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Salir.png"))); // NOI18N
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel14.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel15.setFont(new java.awt.Font("Poiret One", 1, 24)); // NOI18N
        jLabel15.setText("Salir");

        javax.swing.GroupLayout pnl_btnSalirLayout = new javax.swing.GroupLayout(pnl_btnSalir);
        pnl_btnSalir.setLayout(pnl_btnSalirLayout);
        pnl_btnSalirLayout.setHorizontalGroup(
            pnl_btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_btnSalirLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(pnl_btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_btnSalirLayout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_btnSalirLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(96, 96, 96))))
        );
        pnl_btnSalirLayout.setVerticalGroup(
            pnl_btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_btnSalirLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Fondo_panel_botones_principales.jpg"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Poiret One", 2, 70)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/prueba.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl_btnCitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(178, 178, 178)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(pnl_btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnl_btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(pnl_btnJuicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(173, 173, 173)
                        .addComponent(pnl_btnAudiencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(177, 177, 177))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnl_btnClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_btnJuicios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_btnAudiencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_btnCitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl_btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl_btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)))
        );

        jPanel3.setBackground(new java.awt.Color(40, 40, 40));

        lbl_FotoUsuario.setText("");

        lbl_NombreUsuario.setFont(new java.awt.Font("Poiret One", 1, 24)); // NOI18N
        lbl_NombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_NombreUsuario.setText("Usuario");

        pnl_btnAddpersona.setBackground(new java.awt.Color(40, 40, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Añadir Persona");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Add_persona.png"))); // NOI18N

        javax.swing.GroupLayout pnl_btnAddpersonaLayout = new javax.swing.GroupLayout(pnl_btnAddpersona);
        pnl_btnAddpersona.setLayout(pnl_btnAddpersonaLayout);
        pnl_btnAddpersonaLayout.setHorizontalGroup(
            pnl_btnAddpersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_btnAddpersonaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(65, 65, 65))
        );
        pnl_btnAddpersonaLayout.setVerticalGroup(
            pnl_btnAddpersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_btnAddpersonaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_btnAddpersonaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(23, 23, 23))
        );

        pnl_btnInicio.setBackground(new java.awt.Color(40, 40, 40));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Inicio");

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Inicio.png"))); // NOI18N

        javax.swing.GroupLayout pnl_btnInicioLayout = new javax.swing.GroupLayout(pnl_btnInicio);
        pnl_btnInicio.setLayout(pnl_btnInicioLayout);
        pnl_btnInicioLayout.setHorizontalGroup(
            pnl_btnInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_btnInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addGap(46, 46, 46)
                .addComponent(jLabel20)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        pnl_btnInicioLayout.setVerticalGroup(
            pnl_btnInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_btnInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_btnInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pnl_btnAddempleado.setBackground(new java.awt.Color(40, 40, 40));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Añadir Empleado");

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Add_Trabajadores.png"))); // NOI18N

        javax.swing.GroupLayout pnl_btnAddempleadoLayout = new javax.swing.GroupLayout(pnl_btnAddempleado);
        pnl_btnAddempleado.setLayout(pnl_btnAddempleadoLayout);
        pnl_btnAddempleadoLayout.setHorizontalGroup(
            pnl_btnAddempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_btnAddempleadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addGap(29, 29, 29)
                .addComponent(jLabel22)
                .addGap(54, 54, 54))
        );
        pnl_btnAddempleadoLayout.setVerticalGroup(
            pnl_btnAddempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_btnAddempleadoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnl_btnAddempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addGroup(pnl_btnAddempleadoLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel22)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pnl_btnAddusuario.setBackground(new java.awt.Color(40, 40, 40));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Añadir Usuario");

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Add_Usuario.png"))); // NOI18N

        javax.swing.GroupLayout pnl_btnAddusuarioLayout = new javax.swing.GroupLayout(pnl_btnAddusuario);
        pnl_btnAddusuario.setLayout(pnl_btnAddusuarioLayout);
        pnl_btnAddusuarioLayout.setHorizontalGroup(
            pnl_btnAddusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_btnAddusuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addGap(31, 31, 31)
                .addComponent(jLabel24)
                .addGap(52, 52, 52))
        );
        pnl_btnAddusuarioLayout.setVerticalGroup(
            pnl_btnAddusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_btnAddusuarioLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnl_btnAddusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addGroup(pnl_btnAddusuarioLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel24)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(lbl_FotoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnl_btnAddempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(pnl_btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnl_btnAddpersona, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnl_btnAddusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 296, Short.MAX_VALUE))))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_NombreUsuario)
                .addGap(134, 134, 134))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbl_FotoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_NombreUsuario)
                .addGap(43, 43, 43)
                .addComponent(pnl_btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(pnl_btnAddpersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(pnl_btnAddempleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(pnl_btnAddusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(40, 40, 40));

        Btn_minimizarLogin.setBackground(new java.awt.Color(234, 234, 234));
        Btn_minimizarLogin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Btn_minimizarLogin.setForeground(new java.awt.Color(255, 255, 255));
        Btn_minimizarLogin.setText("-");
        Btn_minimizarLogin.setBorder(null);
        Btn_minimizarLogin.setBorderPainted(false);
        Btn_minimizarLogin.setContentAreaFilled(false);
        Btn_minimizarLogin.setDefaultCapable(false);
        Btn_minimizarLogin.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        Btn_cerrarLogin.setBackground(new java.awt.Color(234, 234, 234));
        Btn_cerrarLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn_cerrarLogin.setForeground(new java.awt.Color(255, 255, 255));
        Btn_cerrarLogin.setText("X");
        Btn_cerrarLogin.setBorder(null);
        Btn_cerrarLogin.setBorderPainted(false);
        Btn_cerrarLogin.setContentAreaFilled(false);
        Btn_cerrarLogin.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Btn_minimizarLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_cerrarLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_cerrarLogin)
                    .addComponent(Btn_minimizarLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void pnl_btnClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_btnClientesMouseEntered

    }//GEN-LAST:event_pnl_btnClientesMouseEntered

    private void pnl_btnClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_btnClientesMouseExited

    }//GEN-LAST:event_pnl_btnClientesMouseExited

    private void pnl_btnJuiciosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_btnJuiciosMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnl_btnJuiciosMouseEntered

    private void pnl_btnJuiciosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_btnJuiciosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnl_btnJuiciosMouseExited

    private void pnl_btnAudienciasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_btnAudienciasMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnl_btnAudienciasMouseEntered

    private void pnl_btnAudienciasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_btnAudienciasMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnl_btnAudienciasMouseExited

    private void pnl_btnCitasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_btnCitasMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnl_btnCitasMouseEntered

    private void pnl_btnCitasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_btnCitasMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnl_btnCitasMouseExited

    private void pnl_btnReportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_btnReportesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnl_btnReportesMouseEntered

    private void pnl_btnReportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_btnReportesMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnl_btnReportesMouseExited

    private void pnl_btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_btnSalirMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnl_btnSalirMouseEntered

    private void pnl_btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_btnSalirMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnl_btnSalirMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_cerrarLogin;
    private javax.swing.JButton Btn_minimizarLogin;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private com.bolivia.label.CLabel lbl_FotoUsuario;
    private javax.swing.JLabel lbl_NombreUsuario;
    private javax.swing.JPanel pnl_btnAddempleado;
    private javax.swing.JPanel pnl_btnAddpersona;
    private javax.swing.JPanel pnl_btnAddusuario;
    private javax.swing.JPanel pnl_btnAudiencias;
    private javax.swing.JPanel pnl_btnCitas;
    private javax.swing.JPanel pnl_btnClientes;
    private javax.swing.JPanel pnl_btnInicio;
    private javax.swing.JPanel pnl_btnJuicios;
    private javax.swing.JPanel pnl_btnReportes;
    private javax.swing.JPanel pnl_btnSalir;
    // End of variables declaration//GEN-END:variables
}
