/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mvc.vista;

import LIB.JTexfieldPH_Password;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

/**
 *
 * @author velez
 */
public class Vista_Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Vista_Login() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        initComponents();
    }

    public JTextField getTxtUsuarioLogin() {
        return txtUsuarioLogin;
    }

    public void setTxtUsuarioLogin(JTextField txtUsuarioLogin) {
        this.txtUsuarioLogin = txtUsuarioLogin;
    }

    public JTexfieldPH_Password getTxt_passwordLogin() {
        return txt_passwordLogin;
    }

    public void setTxt_passwordLogin(JTexfieldPH_Password txt_passwordLogin) {
        this.txt_passwordLogin = txt_passwordLogin;
    }

    public JButton getBtn_cerrarLogin() {
        return Btn_cerrarLogin;
    }

    public void setBtn_cerrarLogin(JButton Btn_cerrarLogin) {
        this.Btn_cerrarLogin = Btn_cerrarLogin;
    }

    public JButton getBtn_minimizarLogin() {
        return Btn_minimizarLogin;
    }

    public void setBtn_minimizarLogin(JButton Btn_minimizarLogin) {
        this.Btn_minimizarLogin = Btn_minimizarLogin;
    }

    public JToggleButton getBtn_verContaseña() {
        return Btn_verContaseña;
    }

    public void setBtn_verContaseña(JToggleButton Btn_verContaseña) {
        this.Btn_verContaseña = Btn_verContaseña;
    }

    public JLabel getBtn_login() {
        return btn_login;
    }

    public void setBtn_login(JLabel btn_login) {
        this.btn_login = btn_login;
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_minimizarLogin = new javax.swing.JButton();
        Btn_cerrarLogin = new javax.swing.JButton();
        Btn_verContaseña = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtUsuarioLogin = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txt_passwordLogin = new LIB.JTexfieldPH_Password();
        btn_login = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btn_minimizarLogin.setBackground(new java.awt.Color(234, 234, 234));
        Btn_minimizarLogin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Btn_minimizarLogin.setText("-");
        Btn_minimizarLogin.setBorder(null);
        Btn_minimizarLogin.setBorderPainted(false);
        Btn_minimizarLogin.setContentAreaFilled(false);
        Btn_minimizarLogin.setDefaultCapable(false);
        Btn_minimizarLogin.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(Btn_minimizarLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 30, 20));

        Btn_cerrarLogin.setBackground(new java.awt.Color(234, 234, 234));
        Btn_cerrarLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn_cerrarLogin.setText("X");
        Btn_cerrarLogin.setBorder(null);
        Btn_cerrarLogin.setBorderPainted(false);
        Btn_cerrarLogin.setContentAreaFilled(false);
        Btn_cerrarLogin.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(Btn_cerrarLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 40, -1));

        Btn_verContaseña.setBackground(new java.awt.Color(234, 234, 234));
        Btn_verContaseña.setBorder(null);
        Btn_verContaseña.setBorderPainted(false);
        Btn_verContaseña.setContentAreaFilled(false);
        Btn_verContaseña.setFocusPainted(false);
        getContentPane().add(Btn_verContaseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, 30, 20));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Icon_btn_Sesion.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, -1));

        jLabel9.setFont(new java.awt.Font("Poiret One", 1, 36)); // NOI18N
        jLabel9.setText("Inicio de Sesion");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/User.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Poiret One", 1, 20)); // NOI18N
        jLabel6.setText("Cedula");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, -1, -1));

        txtUsuarioLogin.setBackground(new java.awt.Color(234, 234, 234));
        txtUsuarioLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUsuarioLogin.setBorder(null);
        getContentPane().add(txtUsuarioLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 200, 30));

        jSeparator4.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 200, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/password.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, -1, -1));

        jLabel7.setFont(new java.awt.Font("Poiret One", 1, 20)); // NOI18N
        jLabel7.setText("Contraseña");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 200, 20));

        txt_passwordLogin.setBackground(new java.awt.Color(234, 234, 234));
        txt_passwordLogin.setBorder(null);
        getContentPane().add(txt_passwordLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, -1, -1));

        btn_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Boton_Login.png"))); // NOI18N
        getContentPane().add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Wallpaper Login.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_cerrarLogin;
    private javax.swing.JButton Btn_minimizarLogin;
    private javax.swing.JToggleButton Btn_verContaseña;
    private javax.swing.JLabel btn_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField txtUsuarioLogin;
    private LIB.JTexfieldPH_Password txt_passwordLogin;
    // End of variables declaration//GEN-END:variables
}
